### ISSUE TITLE
Is there a way to change labelSet?

### ISSUE THREAD

**Issue by atvvarna** [flavienliger/DymoWebservice#2]
Hello,
is there a way to change the record.setText on the fly?
Here is the situation using PHP I get list of customers addresses and values were set in the javascript but how I can remove a customer from the Label set?

For example:

```
printLabel = function print() {
        var printers = dymo.label.framework.getPrinters();
        if (printers.length == 0) throw "No DYMO printers are installed. Install DYMO printers.";
        var printerName = "";
        for (var i = 0; i < printers.length; ++i) {
            var printer = printers[i];
            if (printer.printerType == "LabelWriterPrinter") {
                printerName = printer.name;
                break;
            }
        }
        if (printerName == "") throw "No LabelWriter printers found. Install LabelWriter printer";
        var printer = printers[printerName];
        if (!printer) {
            alert("Printer '" + printerName + "' not found");
            return;
        }
        var labelSet = new dymo.label.framework.LabelSetBuilder();
```

var record = labelSet.addRecord(); record.setText('TEXT', 'LABEL1');
var record = labelSet.addRecord(); record.setText('TEXT', 'LABEL2');
var record = labelSet.addRecord(); record.setText('TEXT', 'LABEL3');
            dymo.label.framework.printLabel(printerName, params, labelXml, labelSet);
        }

So before I click the print button I would like to remove LABEL2 and print the rest.

If I can put record.setText('TEXT', 'LABEL2'); in different <script id='remove'> I can use the ID and jquery to remove it.

Any help will be appreciated.

Thanks,
Alex

**Comment by flavienliger** [comment]
Hi,

Why do you not regenerate the labelSet only to send?

For example :

``` Javascript
var sendToPrint = function(labels){
    var labelSet = new dymo.label.framework.LabelSetBuilder();
    var rec;

    for(var i=0; i<labels.length; i++){
        rec = labelSet.addRecord();
        rec.setText(labels[i]);
    }
    // print labelSet
};
```

**Comment by atvvarna** [comment]
I will try. Thanks.

**Comment by atvvarna** [comment]
Thanks for the support.
